In [1]:
import numpy as np

In [7]:
A = np.random.randint(1, 5, size=(5, 4))
A -= np.mean(A) 
u, sig, v = np.linalg.svd(A)

In [8]:
u

array([[-0.35097682, -0.38634577, -0.00711749, -0.07136896, -0.8499459 ],
       [-0.64042854,  0.24244398, -0.60978812, -0.35150559,  0.18887687],
       [-0.42675845, -0.42269251, -0.04938731,  0.73659098,  0.30692491],
       [-0.30150983,  0.76660222,  0.31362081,  0.39447155, -0.25970569],
       [-0.44004046, -0.16003105,  0.7261616 , -0.41614447,  0.2833153 ]])

In [9]:
v

array([[-0.31216055, -0.65251159, -0.4806245 , -0.49576659],
       [ 0.08701277, -0.51730638,  0.83200663, -0.18052108],
       [ 0.63036091,  0.28174542, -0.0473604 , -0.72181828],
       [ 0.70542873, -0.47669934, -0.27298727,  0.4478906 ]])

In [10]:
sig

array([10.66125383,  2.57267446,  2.16365669,  1.42744618])

In [12]:
v @ v.T

array([[ 1.00000000e+00, -2.78445701e-17,  2.24436022e-17,
        -1.07192366e-16],
       [-2.78445701e-17,  1.00000000e+00, -4.21672401e-16,
        -4.68616505e-17],
       [ 2.24436022e-17, -4.21672401e-16,  1.00000000e+00,
         5.30299737e-17],
       [-1.07192366e-16, -4.68616505e-17,  5.30299737e-17,
         1.00000000e+00]])